### ISSUE TITLE
[meta] talk about design goals with customer

### ISSUE THREAD

**Issue by ben243871694** [hpi-swa-teaching/GameMecha#48]
## Story

As a user/developer I want to justify my design decisions with rules and principles we agreed on with the customer.

## Description

**Why:**  
(What value does it have? For whom?)  
**What:**
 - [ ] how much should we implement and how much should be up to swa students
 - [ ] opt-in use?
 - [ ] how easy should it be to understand the code as swa student
 - [ ] how much do you need to know about our implementation when using it

**Comment by ben243871694** [comment]
1. focus on performance problems? 
2. 
3. nope. but document tutorial with text + examples. 
4. not so much..
